//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "eu-west-1_2y9s1s55h"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "404nk8gtbpgf57o40igi9avsio"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .EUWest1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1mesqltn5j608g42bs0gujeejvod4usi8nn8uirqm25c4vst42g2"
